---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastorclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastorclusters/finalizers
  verbs:
  - update
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastorclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastornodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastornodes/finalizers
  verbs:
  - update
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastornodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastorosds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastorosds/finalizers
  verbs:
  - update
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastorosds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastorpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastorpools/finalizers
  verbs:
  - update
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastorpools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1
  resources:
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - v1
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
