# permissions for end users to edit vitastorclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vitastorcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vitastor-operator
    app.kubernetes.io/part-of: vitastor-operator
    app.kubernetes.io/managed-by: kustomize
  name: vitastorcluster-editor-role
rules:
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastorclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastorclusters/status
  verbs:
  - get
