# permissions for end users to view vitastorosds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vitastorosd-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vitastor-operator
    app.kubernetes.io/part-of: vitastor-operator
    app.kubernetes.io/managed-by: kustomize
  name: vitastorosd-viewer-role
rules:
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastorosds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - control.vitastor.io
  resources:
  - vitastorosds/status
  verbs:
  - get
