apiVersion: control.vitastor.io/v1
kind: VitastorCluster
metadata:
  labels:
    app.kubernetes.io/name: vitastorcluster
    app.kubernetes.io/instance: vitastorcluster-sample
    app.kubernetes.io/part-of: vitastor-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vitastor-operator
  name: vitastorcluster-test
spec:
  monitorReplicaNum: 3
  vitastorNodeLabel: "vitastor-node"
  disksReconciligPeriod: 60
  agentImage: "antilles/vitastor-agent:0.8.9"
  monitorImage: "antilles/vitastor-monitor:0.8.9"
  osdImage: "antilles/vitastor-osd:0.8.9"
