---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-vitastor-pvc-block
  namespace: vitastor-system
spec:
  storageClassName: vitastor
  volumeMode: Block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi