apiVersion: control.vitastor.io/v2
kind: VitastorNode
metadata:
  labels:
    app.kubernetes.io/name: vitastor-operator
    app.kubernetes.io/managed-by: kustomize
  name: vitastornode-sample
spec:
  # TODO(user): Add fields here
