apiVersion: control.vitastor.io/v2
kind: VitastorPool
metadata:
  name: vitastorpool-sample
spec:
  scheme: "replicated"
  pgSize: 2
  pgMinSize: 1
  pgCount: 32
  failureDomain: "host"
  vitastorFS: false
  immediateCommit: "none"
