apiVersion: control.vitastor.io/v2
kind: VitastorDisk
metadata:
  name: worker-node-1-sda
  labels:
    control.vitastor.io/cluster: vitastorcluster-sample
    control.vitastor.io/node: worker-node-1
spec:
  devicePath: "/dev/sda"
  nodeRef: "worker-node-1"
  desiredState: "Discovered"
  desiredOSDCount: 1
