//go:build !ignore_autogenerated

/*
Copyright (c) 2025 Dmitry Yusko
SPDX-License-Identifier: GPL-3.0-or-later
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterParameters) DeepCopyInto(out *ClusterParameters) {
	*out = *in
	if in.PlacementLevels != nil {
		in, out := &in.PlacementLevels, &out.PlacementLevels
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterParameters.
func (in *ClusterParameters) DeepCopy() *ClusterParameters {
	if in == nil {
		return nil
	}
	out := new(ClusterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorSpec) DeepCopyInto(out *MonitorSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorSpec.
func (in *MonitorSpec) DeepCopy() *MonitorSpec {
	if in == nil {
		return nil
	}
	out := new(MonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSDSpec) DeepCopyInto(out *OSDSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSDSpec.
func (in *OSDSpec) DeepCopy() *OSDSpec {
	if in == nil {
		return nil
	}
	out := new(OSDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorCluster) DeepCopyInto(out *VitastorCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorCluster.
func (in *VitastorCluster) DeepCopy() *VitastorCluster {
	if in == nil {
		return nil
	}
	out := new(VitastorCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitastorCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorClusterList) DeepCopyInto(out *VitastorClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitastorCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorClusterList.
func (in *VitastorClusterList) DeepCopy() *VitastorClusterList {
	if in == nil {
		return nil
	}
	out := new(VitastorClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitastorClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorClusterSpec) DeepCopyInto(out *VitastorClusterSpec) {
	*out = *in
	in.Agent.DeepCopyInto(&out.Agent)
	in.Monitor.DeepCopyInto(&out.Monitor)
	in.OSD.DeepCopyInto(&out.OSD)
	in.ClusterParameters.DeepCopyInto(&out.ClusterParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorClusterSpec.
func (in *VitastorClusterSpec) DeepCopy() *VitastorClusterSpec {
	if in == nil {
		return nil
	}
	out := new(VitastorClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorClusterStatus) DeepCopyInto(out *VitastorClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorClusterStatus.
func (in *VitastorClusterStatus) DeepCopy() *VitastorClusterStatus {
	if in == nil {
		return nil
	}
	out := new(VitastorClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorDisk) DeepCopyInto(out *VitastorDisk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorDisk.
func (in *VitastorDisk) DeepCopy() *VitastorDisk {
	if in == nil {
		return nil
	}
	out := new(VitastorDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitastorDisk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorDiskList) DeepCopyInto(out *VitastorDiskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitastorDisk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorDiskList.
func (in *VitastorDiskList) DeepCopy() *VitastorDiskList {
	if in == nil {
		return nil
	}
	out := new(VitastorDiskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitastorDiskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorDiskSpec) DeepCopyInto(out *VitastorDiskSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorDiskSpec.
func (in *VitastorDiskSpec) DeepCopy() *VitastorDiskSpec {
	if in == nil {
		return nil
	}
	out := new(VitastorDiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorDiskStatus) DeepCopyInto(out *VitastorDiskStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorDiskStatus.
func (in *VitastorDiskStatus) DeepCopy() *VitastorDiskStatus {
	if in == nil {
		return nil
	}
	out := new(VitastorDiskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorNode) DeepCopyInto(out *VitastorNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorNode.
func (in *VitastorNode) DeepCopy() *VitastorNode {
	if in == nil {
		return nil
	}
	out := new(VitastorNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitastorNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorNodeList) DeepCopyInto(out *VitastorNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitastorNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorNodeList.
func (in *VitastorNodeList) DeepCopy() *VitastorNodeList {
	if in == nil {
		return nil
	}
	out := new(VitastorNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitastorNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorNodeSpec) DeepCopyInto(out *VitastorNodeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorNodeSpec.
func (in *VitastorNodeSpec) DeepCopy() *VitastorNodeSpec {
	if in == nil {
		return nil
	}
	out := new(VitastorNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorNodeStatus) DeepCopyInto(out *VitastorNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorNodeStatus.
func (in *VitastorNodeStatus) DeepCopy() *VitastorNodeStatus {
	if in == nil {
		return nil
	}
	out := new(VitastorNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorOSD) DeepCopyInto(out *VitastorOSD) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorOSD.
func (in *VitastorOSD) DeepCopy() *VitastorOSD {
	if in == nil {
		return nil
	}
	out := new(VitastorOSD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitastorOSD) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorOSDList) DeepCopyInto(out *VitastorOSDList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitastorOSD, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorOSDList.
func (in *VitastorOSDList) DeepCopy() *VitastorOSDList {
	if in == nil {
		return nil
	}
	out := new(VitastorOSDList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitastorOSDList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorOSDSpec) DeepCopyInto(out *VitastorOSDSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorOSDSpec.
func (in *VitastorOSDSpec) DeepCopy() *VitastorOSDSpec {
	if in == nil {
		return nil
	}
	out := new(VitastorOSDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorOSDStatus) DeepCopyInto(out *VitastorOSDStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorOSDStatus.
func (in *VitastorOSDStatus) DeepCopy() *VitastorOSDStatus {
	if in == nil {
		return nil
	}
	out := new(VitastorOSDStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorPool) DeepCopyInto(out *VitastorPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorPool.
func (in *VitastorPool) DeepCopy() *VitastorPool {
	if in == nil {
		return nil
	}
	out := new(VitastorPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitastorPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorPoolList) DeepCopyInto(out *VitastorPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitastorPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorPoolList.
func (in *VitastorPoolList) DeepCopy() *VitastorPoolList {
	if in == nil {
		return nil
	}
	out := new(VitastorPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitastorPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorPoolSpec) DeepCopyInto(out *VitastorPoolSpec) {
	*out = *in
	if in.ParityChunks != nil {
		in, out := &in.ParityChunks, &out.ParityChunks
		*out = new(int32)
		**out = **in
	}
	if in.FailureDomain != nil {
		in, out := &in.FailureDomain, &out.FailureDomain
		*out = new(string)
		**out = **in
	}
	if in.LevelPlacement != nil {
		in, out := &in.LevelPlacement, &out.LevelPlacement
		*out = new(string)
		**out = **in
	}
	if in.RawPlacement != nil {
		in, out := &in.RawPlacement, &out.RawPlacement
		*out = new(string)
		**out = **in
	}
	if in.LocalReads != nil {
		in, out := &in.LocalReads, &out.LocalReads
		*out = new(string)
		**out = **in
	}
	if in.MaxOSDCombinations != nil {
		in, out := &in.MaxOSDCombinations, &out.MaxOSDCombinations
		*out = new(int32)
		**out = **in
	}
	if in.BlockSize != nil {
		in, out := &in.BlockSize, &out.BlockSize
		*out = new(int32)
		**out = **in
	}
	if in.BitmapGranularity != nil {
		in, out := &in.BitmapGranularity, &out.BitmapGranularity
		*out = new(int32)
		**out = **in
	}
	if in.ImmediateCommit != nil {
		in, out := &in.ImmediateCommit, &out.ImmediateCommit
		*out = new(string)
		**out = **in
	}
	if in.OSDTags != nil {
		in, out := &in.OSDTags, &out.OSDTags
		*out = new(string)
		**out = **in
	}
	if in.ScrubInterval != nil {
		in, out := &in.ScrubInterval, &out.ScrubInterval
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorPoolSpec.
func (in *VitastorPoolSpec) DeepCopy() *VitastorPoolSpec {
	if in == nil {
		return nil
	}
	out := new(VitastorPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitastorPoolStatus) DeepCopyInto(out *VitastorPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitastorPoolStatus.
func (in *VitastorPoolStatus) DeepCopy() *VitastorPoolStatus {
	if in == nil {
		return nil
	}
	out := new(VitastorPoolStatus)
	in.DeepCopyInto(out)
	return out
}
